---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
  
  - name: upgrade 
    apt:
      upgrade: yes

  - name: install htop
    apt:
      name: htop
