---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: upgrade
    apt:
      upgrade: yes

  - name: install neofetch
    apt:
      name: neofetch
      state: present

  - name: install htop
    apt:
      name: htop
