---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: uninstall neofetch
    apt:
      name: neofetch
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: uninstall htop
    apt:
      name: htop
      state: absent
    when: ansible_distribution == "Ubuntu"
